FROM arm64v8/openjdk:17
LABEL maintainer="chloepoonpph@gmail.com"
ADD target/bootcamp-sb-crypto-0.0.1-SNAPSHOT.jar bootcamp-sb-crypto-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "bootcamp-sb-crypto-0.0.1-SNAPSHOT.jar"]
EXPOSE 8090